app_configuration:
  semantic_analyzer_host: "192.168.0.10"
  semantic_analyzer_port: "3000"
  sentiments_analyzer_host: "127.0.0.1"
  sentiments_analyzer_port: "5000"
  host: "192.168.0.10"
  port: "3001"