default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: campanarium
  password: campanarium

development:
  <<: *default
  database: campanarium_development

test:
  <<: *default
  database: campanarium_test

production:
  <<: *default
  database: campanarium_production
